name: unjuk_keterampilan
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  d_chart: ^2.6.2
  d_input: ^0.1.1
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
